// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3s_SqHGfHB6TwHD5RRGPKrD03Q0VTuY',
    appId: '1:735612036112:web:8f88ed59843722b9cdd695',
    messagingSenderId: '735612036112',
    projectId: 'test-121-f65b0',
    authDomain: 'test-121-f65b0.firebaseapp.com',
    storageBucket: 'test-121-f65b0.appspot.com',
    measurementId: 'G-T5L8VER0XD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCOaV1FX3-AixqCggNcv1HybMcj1Pe6q0',
    appId: '1:735612036112:ios:5866af915e261399cdd695',
    messagingSenderId: '735612036112',
    projectId: 'test-121-f65b0',
    storageBucket: 'test-121-f65b0.appspot.com',
    iosBundleId: 'com.example.test121',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCOaV1FX3-AixqCggNcv1HybMcj1Pe6q0',
    appId: '1:735612036112:ios:71e86b29eefd147acdd695',
    messagingSenderId: '735612036112',
    projectId: 'test-121-f65b0',
    storageBucket: 'test-121-f65b0.appspot.com',
    iosBundleId: 'com.example.test121.RunnerTests',
  );
}
